services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-review360}
      POSTGRES_USER: ${POSTGRES_USER:-review360}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-review360}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    command: gunicorn review360.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/app
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-insecure}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-1}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,review360-review360-web.i2bzua.easypanel.host}
      POSTGRES_DB: ${POSTGRES_DB:-review360}
      POSTGRES_USER: ${POSTGRES_USER:-review360}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-review360}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      CORS_ALLOW_ALL: 1
      JWT_ACCESS_MIN: 60
      JWT_REFRESH_DAYS: 7
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A review360 worker --loglevel=info
    volumes:
      - .:/app
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-insecure}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-1}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,review360-review360-web.i2bzua.easypanel.host}
      POSTGRES_DB: ${POSTGRES_DB:-review360}
      POSTGRES_USER: ${POSTGRES_USER:-review360}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-review360}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: celery -A review360 beat --loglevel=info
    volumes:
      - .:/app
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-insecure}
      DJANGO_DEBUG: ${DJANGO_DEBUG:-1}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS:-localhost,127.0.0.1,review360-review360-web.i2bzua.easypanel.host}
      POSTGRES_DB: ${POSTGRES_DB:-review360}
      POSTGRES_USER: ${POSTGRES_USER:-review360}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-review360}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
  redis_data:


