# Generated by Django 5.2.6 on 2025-09-12 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0002_user_college_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_of_colleges', to=settings.AUTH_USER_MODEL),
        ),
    ]
