# Generated by Django 5.2.6 on 2025-09-12 11:19

import iam.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0003_college_admin'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', iam.models.UserManager()),
            ],
        ),
    ]
