# Generated by Django 5.2.6 on 2025-09-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='college',
            name='country',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='college',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='college',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
