# Generated by Django 5.2.6 on 2025-09-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iam', '0006_college_created_at_college_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='colleges',
            field=models.ManyToManyField(blank=True, related_name='member_users', to='iam.college'),
        ),
    ]
