# Generated by Django 5.2.6 on 2025-09-12 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_type', models.CharField(choices=[('ADOC', 'ADOC'), ('DRCV', 'DRCV'), ('OTHER', 'OTHER')], max_length=20)),
                ('sheet_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('context', models.TextField(blank=True, default='')),
                ('objectives', models.TextField(blank=True, default='')),
                ('methodology', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('not_started', 'not_started'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('validated', 'validated')], default='not_started', max_length=20)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50)),
                ('record_id', models.BigIntegerField()),
                ('action', models.CharField(choices=[('insert', 'insert'), ('update', 'update'), ('delete', 'delete'), ('login', 'login'), ('import', 'import')], max_length=20)),
                ('details', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='colleges.college')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.PositiveSmallIntegerField()),
                ('academic_year', models.CharField(max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='colleges.college')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_classes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('college', 'name', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('imported_count', models.IntegerField(default=0)),
                ('errors_count', models.IntegerField(default=0)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('class_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to='colleges.class')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_logs', to='colleges.college')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('class_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='colleges.class')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='colleges.college')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('objective', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('rescheduled', 'rescheduled')], default='scheduled', max_length=20)),
                ('google_calendar_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('activity_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='colleges.activitysheet')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_sessions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_sessions', to='colleges.student')),
            ],
        ),
        migrations.AddField(
            model_name='activitysheet',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_sheets', to='colleges.student'),
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_subject', models.BooleanField(blank=True, null=True)),
                ('context_well_formulated', models.BooleanField(blank=True, null=True)),
                ('objectives_validated', models.BooleanField(blank=True, null=True)),
                ('methodology_respected', models.BooleanField(blank=True, null=True)),
                ('session_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('validation_date', models.DateTimeField(auto_now_add=True)),
                ('activity_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='colleges.activitysheet')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='colleges.followupsession')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='activitysheet',
            unique_together={('student', 'sheet_type', 'sheet_number', 'academic_year')},
        ),
    ]
