# Generated by Django 5.2.6 on 2025-09-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_activitysheet_auditlog_class_importlog_student_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupsession',
            name='activity_sheet',
        ),
        migrations.RemoveField(
            model_name='validation',
            name='activity_sheet',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='college',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='class',
            name='college',
        ),
        migrations.RemoveField(
            model_name='class',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_ref',
        ),
        migrations.RemoveField(
            model_name='importlog',
            name='class_ref',
        ),
        migrations.RemoveField(
            model_name='followupsession',
            name='student',
        ),
        migrations.RemoveField(
            model_name='followupsession',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='validation',
            name='session',
        ),
        migrations.RemoveField(
            model_name='importlog',
            name='college',
        ),
        migrations.RemoveField(
            model_name='importlog',
            name='imported_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
        migrations.RemoveField(
            model_name='validation',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='ActivitySheet',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='FollowUpSession',
        ),
        migrations.DeleteModel(
            name='ImportLog',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Validation',
        ),
    ]
