# Generated by Django 5.2.6 on 2025-09-16 11:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('iam', '0001_initial'),
        ('learning', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('activity_sheet_title', models.CharField(blank=True, default='', max_length=255)),
                ('teacher_name', models.CharField(blank=True, default='', max_length=200)),
                ('session_datetime', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('objective', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('scheduled', 'scheduled'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('rescheduled', 'rescheduled')], default='scheduled', max_length=20)),
                ('google_calendar_event_id', models.CharField(blank=True, default='', max_length=255)),
                ('academic_year', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_sessions', to='learning.activitysheet')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_sessions', to='iam.college')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_sessions', to='academics.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
