# Generated by Django 5.2.6 on 2025-09-17 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_department_hod'),
        ('followup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupsession',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_sessions', to='academics.teacher'),
        ),
    ]
