# Generated by Django 5.2.6 on 2025-09-30 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followupsession',
            name='academic_year',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
