# Generated by Django 5.2.6 on 2025-09-30 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0002_fix_academic_year_nullable'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE followup_followupsession ALTER COLUMN academic_year DROP NOT NULL;",
            reverse_sql="ALTER TABLE followup_followupsession ALTER COLUMN academic_year SET NOT NULL;"
        ),
    ]
