# Generated by Django 5.2.6 on 2025-09-24 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_studenttopicprogress'),
        ('followup', '0002_alter_followupsession_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupsession',
            name='notes_for_student',
            field=models.TextField(blank=True, default='', help_text='Notes or instructions for the student'),
        ),
        migrations.AddField(
            model_name='followupsession',
            name='student_topic_progress',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_sessions', to='academics.studenttopicprogress'),
        ),
    ]
