# Generated by Django 5.2.6 on 2025-09-24 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0003_add_student_topic_progress_to_followup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupsession',
            name='student_topic_progress',
        ),
    ]
