# Generated by Django 5.2.6 on 2025-09-24 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0005_fix_topic_title_to_topic_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupsession',
            name='add_to_google_calendar',
            field=models.BooleanField(default=False, help_text='Whether to add this session to Google Calendar'),
        ),
        migrations.AddField(
            model_name='followupsession',
            name='automatic_reminder',
            field=models.BooleanField(default=False, help_text='Whether to send automatic reminder 24 hours in advance'),
        ),
        migrations.AddField(
            model_name='followupsession',
            name='invite_student',
            field=models.BooleanField(default=False, help_text='Whether to send email invitation to student'),
        ),
    ]
