# Generated by Django 5.2.6 on 2025-09-25 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followup', '0006_followupsession_add_to_google_calendar_and_more'),
        ('iam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the field (e.g., 'Classroom A', 'Library', 'Online')", max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Description of the field')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_fields', to='iam.college')),
            ],
            options={
                'indexes': [models.Index(fields=['college', 'is_active'], name='followup_fi_college_98a35c_idx'), models.Index(fields=['name'], name='followup_fi_name_89434b_idx')],
                'unique_together': {('college', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the objective', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the objective')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followup_objectives', to='iam.college')),
            ],
            options={
                'indexes': [models.Index(fields=['college', 'is_active'], name='followup_ob_college_9b9aef_idx'), models.Index(fields=['title'], name='followup_ob_title_2fa719_idx')],
            },
        ),
    ]
