# Generated by Django 5.2.6 on 2025-09-15 11:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('iam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('sheet_type', models.CharField(choices=[('ADOC', 'ADOC'), ('DRCV', 'DRCV'), ('OTHER', 'OTHER')], max_length=20)),
                ('sheet_number', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('context', models.TextField(blank=True, default='')),
                ('objectives', models.TextField(blank=True, default='')),
                ('methodology', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('not_started', 'not_started'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('validated', 'validated')], default='not_started', max_length=20)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_sheets', to='iam.college')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_sheets', to='academics.student')),
            ],
            options={
                'unique_together': {('college', 'student_name', 'sheet_type', 'sheet_number', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_subject', models.BooleanField(default=False)),
                ('context_well_formulated', models.BooleanField(default=False)),
                ('objectives_validated', models.BooleanField(default=False)),
                ('methodology_respected', models.BooleanField(default=False)),
                ('session_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('comments', models.TextField(blank=True, default='')),
                ('validation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='learning.activitysheet')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validations', to='iam.college')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
