# Generated by Django 5.2.6 on 2025-09-22 08:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_alter_subject_unique_together_remove_subject_college_and_more'),
        ('iam', '0001_initial'),
        ('learning', '0002_alter_validation_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('semester', models.IntegerField(blank=True, null=True)),
                ('credits', models.IntegerField(default=0)),
                ('is_elective', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('syllabus_file', models.FileField(blank=True, null=True, upload_to='syllabus/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='iam.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.department')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('context', models.TextField(blank=True, default='', help_text='Context or background information for the topic')),
                ('objectives', models.TextField(blank=True, default='', help_text='Learning objectives for this topic')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('validated', 'Validated')], default='not_started', help_text='Current status of the topic', max_length=20)),
                ('grade', models.PositiveIntegerField(default=0, help_text='Grade for the topic (0-10 scale)')),
                ('comments_and_recommendations', models.TextField(blank=True, default='', help_text='Comments and recommendations about the topic')),
                ('qns1_text', models.TextField(blank=True, default='', help_text='Question 1 text')),
                ('qns1_checked', models.BooleanField(default=False, help_text='Question 1 checkbox')),
                ('qns2_text', models.TextField(blank=True, default='', help_text='Question 2 text')),
                ('qns2_checked', models.BooleanField(default=False, help_text='Question 2 checkbox')),
                ('qns3_text', models.TextField(blank=True, default='', help_text='Question 3 text')),
                ('qns3_checked', models.BooleanField(default=False, help_text='Question 3 checkbox')),
                ('qns4_text', models.TextField(blank=True, default='', help_text='Question 4 text')),
                ('qns4_checked', models.BooleanField(default=False, help_text='Question 4 checkbox')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='learning.subject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['college', 'is_active'], name='learning_su_college_c257f7_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['department', 'semester'], name='learning_su_departm_8eb8cb_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='learning_su_code_398c21_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('college', 'code')},
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['subject', 'is_active'], name='learning_to_subject_859de7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('subject', 'name')},
        ),
    ]