# Generated by Django 5.2.6 on 2025-09-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_subject_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivitySheet',
        ),
        migrations.DeleteModel(
            name='Validation',
        ),
    ]
