# Generated by Django 5.2.6 on 2025-09-23 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_remove_class_subjects'),
        ('iam', '0001_initial'),
        ('learning', '0004_remove_activitysheet_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='class_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.class'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['class_ref', 'is_active'], name='learning_su_class_r_673820_idx'),
        ),
    ]
