# Generated by Django 5.2.6 on 2025-09-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_department_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bulk_upload_errors',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='bulk_upload_file',
            field=models.FileField(blank=True, null=True, upload_to='bulk_uploads/students/'),
        ),
        migrations.AddField(
            model_name='student',
            name='bulk_upload_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bulk_upload_errors',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bulk_upload_file',
            field=models.FileField(blank=True, null=True, upload_to='bulk_uploads/teachers/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='bulk_upload_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
