# Generated by Django 5.2.6 on 2025-09-16 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_alter_class_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='max_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='class',
            name='program',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='class',
            name='room_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
