# Generated by Django 5.2.6 on 2025-09-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_student_bulk_upload_errors_student_bulk_upload_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bulk_upload_errors',
        ),
        migrations.RemoveField(
            model_name='student',
            name='bulk_upload_status',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='bulk_upload_errors',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='bulk_upload_status',
        ),
        migrations.AlterField(
            model_name='student',
            name='bulk_upload_file',
            field=models.FileField(blank=True, null=True, upload_to='student_bulk_uploads/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='bulk_upload_file',
            field=models.FileField(blank=True, null=True, upload_to='teacher_bulk_uploads/'),
        ),
    ]
