# Generated by Django 5.2.6 on 2025-09-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_remove_student_bulk_upload_errors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='bulk_upload_file',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='bulk_upload_file',
        ),
    ]
