# Generated by Django 5.2.6 on 2025-09-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_add_topic_model'),
        ('academics', '0006_remove_student_bulk_upload_file_and_more'),
    ]

    operations = [
    ]
