# Generated by Django 5.2.6 on 2025-09-17 11:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_merge_20250917_1115'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='topic',
            name='academics_topic_subject_name_unique',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='academics_t_subject_a78c75_idx',
            old_name='academics_topic_subject_order_idx',
        ),
        migrations.RenameIndex(
            model_name='topic',
            new_name='academics_t_subject_e234c4_idx',
            old_name='academics_topic_subject_active_idx',
        ),
        migrations.AlterField(
            model_name='topic',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together={('subject', 'name')},
        ),
    ]
