# Generated by Django 5.2.6 on 2025-09-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_remove_topic_academics_topic_subject_name_unique_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employee_id',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('full-time', 'Full-Time'), ('part-time', 'Part-Time'), ('visiting', 'Visiting')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='leaves_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='research_publications',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
