# Generated by Django 5.2.6 on 2025-09-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_make_teacher_fields_optional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportLog',
        ),
    ]
