# Generated by Django 5.2.6 on 2025-09-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_remove_import_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='description',
        ),
        migrations.AddField(
            model_name='topic',
            name='comments',
            field=models.TextField(blank=True, default='', help_text='Comments about the topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='context',
            field=models.TextField(blank=True, default='', help_text='Context or background information for the topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='grade',
            field=models.PositiveIntegerField(default=0, help_text='Grade for the topic (0-10 scale)'),
        ),
        migrations.AddField(
            model_name='topic',
            name='objectives',
            field=models.TextField(blank=True, default='', help_text='Learning objectives for this topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='recommendation',
            field=models.TextField(blank=True, default='', help_text='Recommendations for improvement'),
        ),
        migrations.AddField(
            model_name='topic',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('validated', 'Validated')], default='not_started', help_text='Current status of the topic', max_length=20),
        ),
    ]
