# Generated by Django 5.2.6 on 2025-09-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_remove_topic_description_topic_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['name']},
        ),
        migrations.RemoveIndex(
            model_name='topic',
            name='academics_t_subject_a78c75_idx',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='order',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='topic',
            name='comments_and_recommendations',
            field=models.TextField(blank=True, default='', help_text='Comments and recommendations about the topic'),
        ),
    ]
