# Generated by Django 5.2.6 on 2025-09-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='qns1',
            field=models.BooleanField(default=False, help_text='Question 1'),
        ),
        migrations.AddField(
            model_name='topic',
            name='qns2',
            field=models.BooleanField(default=False, help_text='Question 2'),
        ),
        migrations.AddField(
            model_name='topic',
            name='qns3',
            field=models.BooleanField(default=False, help_text='Question 3'),
        ),
        migrations.AddField(
            model_name='topic',
            name='qns4',
            field=models.BooleanField(default=False, help_text='Question 4'),
        ),
    ]
