# Generated by Django 5.2.6 on 2025-09-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_topic_qns1_topic_qns2_topic_qns3_topic_qns4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='qns1',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='qns2',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='qns3',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='qns4',
        ),
        migrations.AddField(
            model_name='topic',
            name='qns1_checked',
            field=models.BooleanField(default=False, help_text='Question 1 checkbox'),
        ),
        migrations.AddField(
            model_name='topic',
            name='qns1_text',
            field=models.TextField(blank=True, default='', help_text='Question 1 text'),
        ),
        migrations.AddField(
            model_name='topic',
            name='qns2_checked',
            field=models.BooleanField(default=False, help_text='Question 2 checkbox'),
        ),
        migrations.AddField(
            model_name='topic',
            name='qns2_text',
            field=models.TextField(blank=True, default='', help_text='Question 2 text'),
        ),
        migrations.AddField(
            model_name='topic',
            name='qns3_checked',
            field=models.BooleanField(default=False, help_text='Question 3 checkbox'),
        ),
        migrations.AddField(
            model_name='topic',
            name='qns3_text',
            field=models.TextField(blank=True, default='', help_text='Question 3 text'),
        ),
        migrations.AddField(
            model_name='topic',
            name='qns4_checked',
            field=models.BooleanField(default=False, help_text='Question 4 checkbox'),
        ),
        migrations.AddField(
            model_name='topic',
            name='qns4_text',
            field=models.TextField(blank=True, default='', help_text='Question 4 text'),
        ),
    ]
