# Generated by Django 5.2.6 on 2025-09-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_remove_topic_qns1_remove_topic_qns2_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subject',
            name='college',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='department',
        ),
    ]
