# Generated by Django 5.2.6 on 2025-09-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_alter_subject_unique_together_remove_subject_college_and_more'),
        ('learning', '0003_subject_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subjects_handled',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='learning.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
