# Generated by Django 5.2.6 on 2025-09-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_make_student_fields_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
