# Generated by Django 5.2.6 on 2025-09-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_add_metadata_to_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='max_students',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
