# Generated by Django 5.2.6 on 2025-09-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_make_max_students_optional'),
        ('learning', '0004_remove_activitysheet_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects taught in this class', related_name='classes', to='learning.subject'),
        ),
    ]
