# Generated by Django 5.2.6 on 2025-09-23 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_class_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='subjects',
        ),
    ]
