# Generated by Django 5.2.6 on 2025-09-24 06:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_remove_class_subjects'),
        ('learning', '0005_subject_class_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subject_assignments', to='academics.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subjects', to='academics.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to='learning.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_assignments', to='academics.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'is_active'], name='academics_s_student_1a12e0_idx'), models.Index(fields=['subject', 'is_active'], name='academics_s_subject_f3797b_idx'), models.Index(fields=['teacher', 'is_active'], name='academics_s_teacher_32769f_idx'), models.Index(fields=['class_ref', 'is_active'], name='academics_s_class_r_60ae94_idx')],
                'unique_together': {('student', 'subject', 'class_ref')},
            },
        ),
    ]
