# Generated by Django 5.2.6 on 2025-09-24 10:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_studentsubject'),
        ('learning', '0005_subject_class_ref_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentTopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('validated', 'Validated')], default='not_started', help_text="Student's current status on this topic", max_length=20)),
                ('grade', models.PositiveIntegerField(default=0, help_text="Student's grade for this topic (0-10 scale)")),
                ('comments_and_recommendations', models.TextField(blank=True, default='', help_text="Comments and recommendations about the student's progress on this topic")),
                ('qns1_text', models.TextField(blank=True, default='', help_text='Question 1 text')),
                ('qns1_checked', models.BooleanField(default=False, help_text='Question 1 checkbox')),
                ('qns2_text', models.TextField(blank=True, default='', help_text='Question 2 text')),
                ('qns2_checked', models.BooleanField(default=False, help_text='Question 2 checkbox')),
                ('qns3_text', models.TextField(blank=True, default='', help_text='Question 3 text')),
                ('qns3_checked', models.BooleanField(default=False, help_text='Question 3 checkbox')),
                ('qns4_text', models.TextField(blank=True, default='', help_text='Question 4 text')),
                ('qns4_checked', models.BooleanField(default=False, help_text='Question 4 checkbox')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_topic_progress', to='academics.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to='academics.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_topic_progress', to='learning.subject')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='learning.topic')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'is_active'], name='academics_s_student_3dee5a_idx'), models.Index(fields=['topic', 'is_active'], name='academics_s_topic_i_47f829_idx'), models.Index(fields=['subject', 'is_active'], name='academics_s_subject_4d61bd_idx'), models.Index(fields=['class_ref', 'is_active'], name='academics_s_class_r_baa9c5_idx'), models.Index(fields=['status'], name='academics_s_status_8c6c1b_idx')],
                'unique_together': {('student', 'topic', 'class_ref')},
            },
        ),
    ]
