# Generated by Django 5.2.6 on 2025-09-25 07:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_make_student_user_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_enrollments', to='academics.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to='academics.student')),
            ],
            options={
                'indexes': [models.Index(fields=['student', 'is_active'], name='academics_s_student_1b31c8_idx'), models.Index(fields=['class_ref', 'is_active'], name='academics_s_class_r_4e65ce_idx'), models.Index(fields=['enrolled_at'], name='academics_s_enrolle_d5ed92_idx')],
                'unique_together': {('student', 'class_ref')},
            },
        ),
    ]
