# Generated by Django 5.2.6 on 2025-09-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0026_add_student_class_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttopicprogress',
            name='draft_comments_and_recommendations',
            field=models.TextField(blank=True, default='', help_text='Draft comments (temporary)'),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='draft_grade',
            field=models.PositiveIntegerField(blank=True, help_text='Draft grade (temporary)', null=True),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='draft_qns1_checked',
            field=models.BooleanField(default=False, help_text='Draft Question 1 checkbox'),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='draft_qns1_text',
            field=models.TextField(blank=True, default='', help_text='Draft Question 1 text'),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='draft_qns2_checked',
            field=models.BooleanField(default=False, help_text='Draft Question 2 checkbox'),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='draft_qns2_text',
            field=models.TextField(blank=True, default='', help_text='Draft Question 2 text'),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='draft_qns3_checked',
            field=models.BooleanField(default=False, help_text='Draft Question 3 checkbox'),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='draft_qns3_text',
            field=models.TextField(blank=True, default='', help_text='Draft Question 3 text'),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='draft_qns4_checked',
            field=models.BooleanField(default=False, help_text='Draft Question 4 checkbox'),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='draft_qns4_text',
            field=models.TextField(blank=True, default='', help_text='Draft Question 4 text'),
        ),
        migrations.AddField(
            model_name='studenttopicprogress',
            name='draft_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('validated', 'Validated')], help_text='Draft status (temporary)', max_length=20, null=True),
        ),
    ]
