# Generated by Django 5.2.6 on 2025-09-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0027_studenttopicprogress_draft_comments_and_recommendations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttopicprogress',
            name='draft_grade',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Draft grade (temporary)', max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='studenttopicprogress',
            name='grade',
            field=models.DecimalField(decimal_places=1, default=0, help_text="Student's grade for this topic (0-10 scale)", max_digits=3),
        ),
    ]
