# Generated by Django 5.2.6 on 2025-09-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0028_alter_studenttopicprogress_draft_grade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenttopicprogress',
            name='is_draft',
            field=models.BooleanField(default=False, help_text='Whether this record is a draft'),
        ),
    ]
