# Generated by Django 5.2.6 on 2025-09-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0029_studenttopicprogress_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studenttopicprogress',
            name='draft_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('validated', 'Validated'), ('draft', 'Draft')], help_text='Draft status (temporary)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studenttopicprogress',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('validated', 'Validated'), ('draft', 'Draft')], default='not_started', help_text="Student's current status on this topic", max_length=20),
        ),
    ]
